-- ========================================
-- Clutch - Supabase Database Setup
-- Run this in Supabase SQL Editor
-- ========================================

-- Users table
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  name TEXT NOT NULL,
  university TEXT NOT NULL,
  bio TEXT DEFAULT '',
  phone TEXT DEFAULT '',
  rating FLOAT DEFAULT 0,
  total_reviews INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tasks table
CREATE TABLE IF NOT EXISTS tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  poster_id BIGINT NOT NULL REFERENCES users(id),
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  category TEXT NOT NULL,
  fee FLOAT NOT NULL,
  location TEXT DEFAULT '',
  due_date TEXT,
  status TEXT DEFAULT 'open' CHECK(status IN ('open','accepted','in_progress','completed','cancelled')),
  accepted_by BIGINT REFERENCES users(id),
  accepted_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Messages table
CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id BIGINT NOT NULL REFERENCES tasks(id),
  sender_id BIGINT NOT NULL REFERENCES users(id),
  receiver_id BIGINT NOT NULL REFERENCES users(id),
  content TEXT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Reviews table
CREATE TABLE IF NOT EXISTS reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id BIGINT NOT NULL REFERENCES tasks(id),
  reviewer_id BIGINT NOT NULL REFERENCES users(id),
  reviewee_id BIGINT NOT NULL REFERENCES users(id),
  rating INTEGER NOT NULL CHECK(rating >= 1 AND rating <= 5),
  comment TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(task_id, reviewer_id)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status);
CREATE INDEX IF NOT EXISTS idx_tasks_poster ON tasks(poster_id);
CREATE INDEX IF NOT EXISTS idx_tasks_accepted_by ON tasks(accepted_by);
CREATE INDEX IF NOT EXISTS idx_messages_task ON messages(task_id);
CREATE INDEX IF NOT EXISTS idx_messages_sender ON messages(sender_id);
CREATE INDEX IF NOT EXISTS idx_messages_receiver ON messages(receiver_id);

-- Row Level Security (allow all - we handle auth in Express)
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all" ON users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all" ON tasks FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all" ON messages FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all" ON reviews FOR ALL USING (true) WITH CHECK (true);

-- ========================================
-- RPC Function: get_conversations
-- Returns conversation list for a user
-- ========================================
CREATE OR REPLACE FUNCTION get_conversations(p_user_id BIGINT)
RETURNS TABLE (
  task_id BIGINT,
  task_title TEXT,
  task_status TEXT,
  other_user_id BIGINT,
  other_user_name TEXT,
  last_message TEXT,
  last_message_at TIMESTAMPTZ,
  unread_count BIGINT
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    m.task_id,
    t.title AS task_title,
    t.status AS task_status,
    CASE WHEN m.sender_id = p_user_id THEN m.receiver_id ELSE m.sender_id END AS other_user_id,
    u.name AS other_user_name,
    m.content AS last_message,
    m.created_at AS last_message_at,
    (SELECT COUNT(*) FROM messages m2
     WHERE m2.task_id = m.task_id
     AND m2.receiver_id = p_user_id
     AND m2.sender_id = CASE WHEN m.sender_id = p_user_id THEN m.receiver_id ELSE m.sender_id END
     AND m2.is_read = false) AS unread_count
  FROM messages m
  JOIN tasks t ON m.task_id = t.id
  JOIN users u ON u.id = CASE WHEN m.sender_id = p_user_id THEN m.receiver_id ELSE m.sender_id END
  WHERE m.id IN (
    SELECT MAX(m3.id) FROM messages m3
    WHERE m3.sender_id = p_user_id OR m3.receiver_id = p_user_id
    GROUP BY m3.task_id, CASE WHEN m3.sender_id = p_user_id THEN m3.receiver_id ELSE m3.sender_id END
  )
  ORDER BY m.created_at DESC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
